In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [36]:
data = pd.read_csv("data/train.csv") 
#剔除变量  
# print(data['Sex'])
le_sex=LabelEncoder().fit(data['Sex'])
# print("le_sex:", le_sex)
Sex_label=le_sex.transform(data['Sex'])
# print(Sex_label)
ohe_sex=OneHotEncoder(sparse=False).fit(Sex_label.reshape(-1,1))
# print(ohe_sex)
Sex_ohe=ohe_sex.transform(Sex_label.reshape(-1,1))
print(Sex_ohe)

[[ 0.  1.]
 [ 1.  0.]
 [ 1.  0.]
 ..., 
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  1.]]


In [11]:
le = LabelEncoder()
print(le)

LabelEncoder()


In [52]:
ll = le.fit([1, 5, 5, 200, 5, 1])
le.classes_ 
ll.classes_

array([  1,   5, 200])

In [51]:
label = le.transform([1, 5, 5, 200, 5, 1])
print(label)
label

[0 1 1 2 1 0]


array([0, 1, 1, 2, 1, 0])

In [24]:
one = OneHotEncoder()

In [30]:
one.fit([[1],[2],[3],[4]])

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [33]:
one.transform([[2],[2],[3],[4]]).toarray()

array([[ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [57]:
enc = OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1],[1, 0, 2]])
print("enc.n_values_ is:",enc.n_values_)
print("enc.feature_indices_ is:",enc.feature_indices_)
print(enc.transform([[0, 2, 2]]).toarray())

enc.n_values_ is: [2 3 4]
enc.feature_indices_ is: [0 2 5 9]
[[ 1.  0.  0.  0.  1.  0.  0.  1.  0.]]


每一列代表一个属性，fit 操作之后：
对象enc的n_values_成员变量，记录着每一个属性的最大取值数目，如本例第一个属性：0, 1, 0, 1 ⇒ 2，0, 1, 2, 0 ⇒ 3，3, 0, 1, 2 ⇒ 4

即各个属性（feature）在 one hot 编码下占据的位数

对象 enc 的 feature_indices_，则记录着属性在新 One hot 编码下的索引位置，

feature_indices_ 是对 n_values_ 的累积值，不过 feature_indices 的首位是 0；

进一步通过 fit 好的 one hot encoder 对新来的特征向量进行编码：

enc.transform([[0, 1, 1]]).toarray()

array([[ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.]])

前 2 位 1, 0，对 0 进行编码

中间 3 位 0, 1, 0 对 1 进行编码

末尾 4 位 0, 1, 0, 0 对 1 进行编码